# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-format
      - id: ruff-check

  - repo: local
    hooks:
      - id: check-protected-branches
        name: check-protected-branches
        entry: ./.hooks/check-protected-branches.sh
        language: script
        stages: [pre-commit]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: check-branch-naming
        name: check-branch-naming
        entry: ./.hooks/check-branch-naming.sh
        language: script
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
