services:
  db:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  postgres_data:
  localstack_data:
