"""add_restaurants_table

Revision ID: 20ae4de7d56a
Revises: b2c3d4e5f678
Create Date: 2026-04-07 19:01:38.659989

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20ae4de7d56a"
down_revision = "b2c3d4e5f678"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restaurants")
    # ### end Alembic commands ###
